public class Tester {
    public static void main(String[] args) {
        int x1 = -1;
        int y1 = 5;
        int x2 = 3;
        int y2 = 10;
        LinearEquation equation = new LinearEquation(x1, y1, x2, y2);
        System.out.println("Equation: " + equation.equation());
        System.out.println("Slope: " + equation.slope());
        System.out.println("y-intercept: " + equation.yIntercept());
        System.out.println("Distance: " + equation.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation.lineInfo());
        System.out.println();
        double testX = 4;
        System.out.println("Coordinate for x: " + equation.coordinateForX(testX));
        System.out.println("-------------------------------------------------------------------------------");

        int x3 = 2;
        int y3 = 10;
        int x4 = -1;
        int y4 = 3;
        LinearEquation equation1 = new LinearEquation(x3, y3, x4, y4);
        System.out.println("Equation: " + equation1.equation());
        System.out.println("Slope: " + equation1.slope());
        System.out.println("y-intercept: " + equation1.yIntercept());
        System.out.println("Distance: " + equation1.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation1.lineInfo());
        System.out.println();
        double testX1 = 4;
        System.out.println("Coordinate for x: " + equation1.coordinateForX(testX1));
        System.out.println("-------------------------------------------------------------------------------");

        int x5 = -6;
        int y5 = -2;
        int x6 = 1;
        int y6 = -1;
        LinearEquation equation2 = new LinearEquation(x5, y5, x6, y6);
        System.out.println("Equation: " + equation2.equation());
        System.out.println("Slope: " + equation2.slope());
        System.out.println("y-intercept: " + equation2.yIntercept());
        System.out.println("Distance: " + equation2.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation2.lineInfo());
        System.out.println();
        double testX2 = 4;
        System.out.println("Coordinate for x: " + equation2.coordinateForX(testX2));
        System.out.println("-------------------------------------------------------------------------------");

        int x7 = 1;
        int y7 = 4;
        int x8 = 7;
        int y8 = 12;
        LinearEquation equation3 = new LinearEquation(x7, y7, x8, y8);
        System.out.println("Equation: " + equation3.equation());
        System.out.println("Slope: " + equation3.slope());
        System.out.println("y-intercept: " + equation3.yIntercept());
        System.out.println("Distance: " + equation3.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation3.lineInfo());
        System.out.println();
        double testX3 = 4;
        System.out.println("Coordinate for x: " + equation3.coordinateForX(testX3));
        System.out.println("-------------------------------------------------------------------------------");

        int x9 = 0;
        int y9 = 0;
        int x10 = 4;
        int y10 = 5;
        LinearEquation equation4 = new LinearEquation(x9, y9, x10, y10);
        System.out.println("Equation: " + equation4.equation());
        System.out.println("Slope: " + equation4.slope());
        System.out.println("y-intercept: " + equation4.yIntercept());
        System.out.println("Distance: " + equation4.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation4.lineInfo());
        System.out.println();
        double testX4 = 4;
        System.out.println("Coordinate for x: " + equation4.coordinateForX(testX4));
        System.out.println("-------------------------------------------------------------------------------");

        int x11 = -1;
        int y11 = 4;
        int x12 = -7;
        int y12 = 12;
        LinearEquation equation5 = new LinearEquation(x11, y11, x12, y12);
        System.out.println("Equation: " + equation5.equation());
        System.out.println("Slope: " + equation5.slope());
        System.out.println("y-intercept: " + equation5.yIntercept());
        System.out.println("Distance: " + equation5.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation5.lineInfo());
        System.out.println();
        double testX5 = 4;
        System.out.println("Coordinate for x: " + equation5.coordinateForX(testX5));
        System.out.println("-------------------------------------------------------------------------------");

        int x13 = 6;
        int y13 = 3;
        int x14 = -1;
        int y14 = 4;
        LinearEquation equation6 = new LinearEquation(x13, y13, x14, y14);
        System.out.println("Equation: " + equation6.equation());
        System.out.println("Slope: " + equation6.slope());
        System.out.println("y-intercept: " + equation6.yIntercept());
        System.out.println("Distance: " + equation6.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation6.lineInfo());
        System.out.println();
        double testX6 = 4;
        System.out.println("Coordinate for x: " + equation6.coordinateForX(testX6));
        System.out.println("-------------------------------------------------------------------------------");

        int x15 = 4;
        int y15 = 0;
        int x16 = 6;
        int y16 = 10;
        LinearEquation equation7 = new LinearEquation(x15, y15, x16, y16);
        System.out.println("Equation: " + equation7.equation());
        System.out.println("Slope: " + equation7.slope());
        System.out.println("y-intercept: " + equation7.yIntercept());
        System.out.println("Distance: " + equation7.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation7.lineInfo());
        System.out.println();
        double testX7 = 4;
        System.out.println("Coordinate for x: " + equation7.coordinateForX(testX7));
        System.out.println("-------------------------------------------------------------------------------");

        int x17 = 6;
        int y17 = 2;
        int x18 = 8;
        int y18 = -12;
        LinearEquation equation8 = new LinearEquation(x17, y17, x18, y18);
        System.out.println("Equation: " + equation8.equation());
        System.out.println("Slope: " + equation8.slope());
        System.out.println("y-intercept: " + equation8.yIntercept());
        System.out.println("Distance: " + equation8.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation8.lineInfo());
        System.out.println();
        double testX8 = 4;
        System.out.println("Coordinate for x: " + equation8.coordinateForX(testX8));
        System.out.println("-------------------------------------------------------------------------------");

        int x19 = 1;
        int y19 = -10;
        int x20 = -3;
        int y20 = 2;
        LinearEquation equation9 = new LinearEquation(x19, y19, x20, y20);
        System.out.println("Equation: " + equation9.equation());
        System.out.println("Slope: " + equation9.slope());
        System.out.println("y-intercept: " + equation9.yIntercept());
        System.out.println("Distance: " + equation9.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation9.lineInfo());
        System.out.println();
        double testX9 = 4;
        System.out.println("Coordinate for x: " + equation9.coordinateForX(testX9));
        System.out.println("-------------------------------------------------------------------------------");

        int x45 = 7;
        int y45 = 14;
        int x21 = 5;
        int y21 = 10;
        LinearEquation equation10 = new LinearEquation(x45, y45, x21, y21);
        System.out.println("Equation: " + equation10.equation());
        System.out.println("Slope: " + equation10.slope());
        System.out.println("y-intercept: " + equation10.yIntercept());
        System.out.println("Distance: " + equation10.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation10.lineInfo());
        System.out.println();
        double testX10 = 4;
        System.out.println("Coordinate for x: " + equation10.coordinateForX(testX10));
        System.out.println("-------------------------------------------------------------------------------");

        int x22 = -1;
        int y22 = 3;
        int x23 = 2;
        int y23 = 6;
        LinearEquation equation11 = new LinearEquation(x22, y22, x23, y23);
        System.out.println("Equation: " + equation11.equation());
        System.out.println("Slope: " + equation11.slope());
        System.out.println("y-intercept: " + equation11.yIntercept());
        System.out.println("Distance: " + equation11.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation11.lineInfo());
        System.out.println();
        double testX11 = 4;
        System.out.println("Coordinate for x: " + equation11.coordinateForX(testX11));
        System.out.println("-------------------------------------------------------------------------------");

        int x24 = -1;
        int y24 = 2;
        int x25 = -3;
        int y25 = 4;
        LinearEquation equation12 = new LinearEquation(x24, y24, x25, y25);
        System.out.println("Equation: " + equation12.equation());
        System.out.println("Slope: " + equation12.slope());
        System.out.println("y-intercept: " + equation12.yIntercept());
        System.out.println("Distance: " + equation12.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation12.lineInfo());
        System.out.println();
        double testX12 = 4;
        System.out.println("Coordinate for x: " + equation12.coordinateForX(testX12));
        System.out.println("-------------------------------------------------------------------------------");

        int x26 = -2;
        int y26 = -2;
        int x27= 4;
        int y27 = 4;
        LinearEquation equation13 = new LinearEquation(x26, y26, x27, y27);
        System.out.println("Equation: " + equation13.equation());
        System.out.println("Slope: " + equation13.slope());
        System.out.println("y-intercept: " + equation13.yIntercept());
        System.out.println("Distance: " + equation13.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation13.lineInfo());
        System.out.println();
        double testX13 = 4;
        System.out.println("Coordinate for x: " + equation13.coordinateForX(testX));
        System.out.println("-------------------------------------------------------------------------------");

        int x28 = 7;
        int y28 = 12;
        int x29 = 3;
        int y29 = 12;
        LinearEquation equation14 = new LinearEquation(x28, y28, x29, y29);
        System.out.println("Equation: " + equation14.equation());
        System.out.println("Slope: " + equation14.slope());
        System.out.println("y-intercept: " + equation14.yIntercept());
        System.out.println("Distance: " + equation14.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation14.lineInfo());
        System.out.println();
        double testX14 = 4;
        System.out.println("Coordinate for x: " + equation14.coordinateForX(testX14));
        System.out.println("-------------------------------------------------------------------------------");

        int x30 = 16;
        int y31 = -2;
        int x32 = 3;
        int y32 = -2;
        LinearEquation equation15 = new LinearEquation(x30, y31, x32, y32);
        System.out.println("Equation: " + equation15.equation());
        System.out.println("Slope: " + equation15.slope());
        System.out.println("y-intercept: " + equation15.yIntercept());
        System.out.println("Distance: " + equation15.distance());
        System.out.println();
        System.out.println("----- Line info -----");
        System.out.println(equation15.lineInfo());
        System.out.println();
        double testX15 = 4;
        System.out.println("Coordinate for x: " + equation15.coordinateForX(testX15));
        System.out.println("-------------------------------------------------------------------------------");


    }
}
